package com.yanwang.employeemanagement.controller;

import com.yanwang.employeemanagement.service.HomeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

@Controller // This means that this class is a Controller
public class HomeController {

	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use an homeService for each
	HomeService homeService;

	//	display chart
	@GetMapping("/")
	// This means that this method will be executed when user sends GET Requests to "/"
	// In our case, "http://localhost:8080/"
	public String viewHomePage(Model model) {

		//	We can use this attribute "chartDataList" to perform server-side rendering of the HTML with using Thymeleaf.
		//	We set all chart data as "chartDataList"
		model.addAttribute("chartData", homeService.getChartData());

		//  shows the index.html template:
		return "index";
	}
}
