package com.yanwang.employeemanagement.service;

import com.yanwang.employeemanagement.domain.Company;
import com.yanwang.employeemanagement.repository.CompanyRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service // This means that this class is a service
public class CompanyService {
	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data
	CompanyRepository companyRepository;

	//	get all companies
	public List<Company> getAllCompanies() {

		// find all companies data, then return it
		return companyRepository.findAll();
	}

	// save a company
	public void saveCompany(Company cmp) {
		// save company data to database
		companyRepository.save(cmp);
	}

	//	get company by id
	public Company getCompanyById(Long id) {
		// find a company by id
		Company cmp = companyRepository.getById(id);

		// if there is not a company who has the id, throw the error.
		if (cmp == null) {
			throw new RuntimeException("Company not found");
		}
		return cmp;
	}

	//	delete company by id
	public String deleteCompanyById(Long id) {
		// find a company by id
		Company cmp = companyRepository.getById(id);

		// if there is not a company who has the id, throw the error.
		if (cmp == null) {
			throw new RuntimeException("Company not found");
		}

		// delete a company who has the id from the database
		companyRepository.deleteById(id);
		return "Deleted: " + cmp.getCompanyName();
	}
}
