package com.yanwang.employeemanagement.service;

import com.yanwang.employeemanagement.repository.EmployeeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

@Service // This means that this class is a service
public class HomeService {
	@Autowired
	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data
	EmployeeRepository employeeRepository;

	//	get number of employee for chart data
	public List<List<Object>> getChartData() {

		// get number of employee, then return it
		List<Object[]> result  = employeeRepository.getNumberOfEmployee();
		List<List<Object>> ret = new ArrayList<List<Object>>();
		for (Object[] item:result) {
			ret.add(List.of(item[0].toString(), item[1]));
		}
		return ret;
	}
}
